### PR TITLE
Fix a gcc10 compilation error

### PR DESCRIPTION
**Pull request by desertfire**
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* __->__ #319

Summary: see the log at https://github.com/pytorch/pytorch/actions/runs/4907784291/jobs/8764266404

Differential Revision: [D45667303](https://our.internmc.facebook.com/intern/diff/D45667303)

### CODE REVIEW

**Review by wconstab — APPROVED** [review]
Stamping to unblock, Also keep in mind you'll have to advance the CI pin on the pytorch side - you may have seen my recent PR last week.

**Comment by desertfire** [comment]
@wconstab , looks like all the tests are queued. Do you know if I have to checkin from the fbcode side?

**Comment by wconstab** [comment]
I landed to multipy repo without CI passing, it appeared to be in a broken trunk state before my merge. Not sure what to do here.

**Comment by desertfire** [comment]
@desertfire has imported this pull request.  If you are a Meta employee, you can view this diff [on Phabricator](https://www.internalfb.com/diff/D45667303).

**Pull request closed without merging**
